// Code generated by hertz generator.

package main

import (
	"blog_hertz/biz/dal"
	"blog_hertz/biz/mw"
	"os"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {
	f, err := os.OpenFile("./biz/logs/tag.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	hlog.SetOutput(f)

	dal.Init()
	h := server.Default()

	h.Use(mw.AccessLog())
	register(h)
	h.Spin()
}
